apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
      team: awesome
  template:
    metadata:
      labels:
        app: nginx
        team: awesome
    spec:
      containers:
      - name: nginx
        image: axelsirota/versioned-nginx:1.0
