apiVersion: v1
kind: Pod
metadata:
  name: loadtester
spec:
  containers:
  - name: loader
    image: bunchjesse/loadtest
    env:
      - name: NUM_USERS
        value: "100"  # Number of concurrent users or requests
      - name: URL
        value: "http://flask-microservice.default.svc.cluster.local:80"  # Target your Flask service
      - name: DURATION
        value: "20000"  # Duration of the test in milliseconds
