apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: default
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80           # Port Grafana is exposed on internally
      targetPort: 3000    # Port Grafana container listens on
      nodePort: 30001     # NodePort to access Grafana externally
