apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-exporter
  template:
    metadata:
      labels:
        app: prometheus-exporter
    spec:
      containers:
      - name: prometheus-exporter
        image: axelsirota/prometheus-exporter:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter-service
  namespace: default
  labels:
    app.kubernetes.io/part-of: dms
    app: prometheus-exporter
  annotations:
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: prometheus-exporter
  ports:
    - name: http  # Adding a name to match the ServiceMonitor
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-exporter-servicemonitor
  namespace: default
  labels:
    prometheus: monitoring  # Ensure this matches your Helm configuration
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dms # Match labels for your Service
  endpoints:
    - port: http  # Matches the port name in the Service
      path: /metrics
      interval: 15s