apiVersion: v1
kind: Service
metadata:
  name: microservice-a-service
spec:
  selector:
    app: microservice-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Expose on this NodePort
  type: NodePort
